name: CI Tests
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  shellcheck:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout repository
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 #v5.0.0
      with:
        fetch-depth: 0 # Differential ShellCheck requires full git history

    - name: Differential ShellCheck
      uses: redhat-plumbers-in-action/differential-shellcheck@0d9e5b29625f871e6a4215380486d6f1a7cb6cdd #v5.5.5
      with:
        severity: warning
        display-engine: sarif-fmt

    - name: Spell-Checking
      uses: codespell-project/actions-codespell@406322ec52dd7b488e48c1c4b82e2a8b3a1bf630 #v2.1
      with:
        ignore_words_file: .codespellignore

    - name: Get editorconfig-checker
      uses: editorconfig-checker/action-editorconfig-checker@1a41284d59c6fe7f1b21ddc4a2b36400a33dc1b4 # tag v2 is really out of date

    - name: Run editorconfig-checker
      run: editorconfig-checker
